name: 🚀 Build and Deploy Pycade Bomber to Web

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 📦 Checkout Repository
        uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install --no-dependencies pybag
          pip install flake8

      - name: 🧪 Verify Template File Presence
        run: |
          echo "🔍 Checking for custom index.html.template..."
          test -f web/index.html.template && echo "✅ Template found!" || echo "❌ Template missing!"

      - name: 🏗️ Build Web Version with Pygbag
        timeout-minutes: 30
        run: |
          echo "🔧 Building web version with pygbag..."
          python -m pygbag --build --archive --disable-sound-format-error .
          echo "✅ Pygbag build completed."

      - name: 🔎 Verify Build Output
        run: |
          echo "📁 Checking contents of build/web..."
          ls -R build/web
          if [ -d "build/web" ] && [ "$(ls -A build/web)" ]; then
            echo "✅ build/web is valid and not empty."
          else
            echo "❌ Error: build/web is empty or missing!"
            exit 1
          fi

      - name: 📤 Upload GitHub Pages Artifact
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web

      - name: 🚀 Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        id: deployment
        uses: actions/deploy-pages@v4
