name: Build and Deploy Pycade Bomber to Web

on:
  push:
    branches:
      - main # 或 'master'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # pygame
          pip install pygbag            # pygbag 0.9.2

      - name: Build Web Version with Pygbag
        timeout-minutes: 30
        run: |
          echo "Starting pygbag build with explicit main, assets, and directory..."
          # 這是最穩健的混合式指令，能避免分析卡住和執行時 404 的問題
          if ! pygbag --build --main main.py --assets . ; then
            echo "Pygbag command failed!"
            ls -la
            exit 1
          fi
          echo "Pygbag build command finished successfully."

      - name: Verify build output
        run: |
          echo "Verifying build output..."
          echo "Listing contents of build/web directory:"
          ls -R build/web
          if [ -d "build/web" ] && [ "$(ls -A build/web)" ]; then
            echo "build/web directory is valid and contains files."
          else
            echo "Error: build/web directory is empty or does not exist after pygbag build."
            exit 1 
          fi

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4