name: 🧪 Run Pygame Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Run-Pygame-Tests:
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout repository
        uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: 🧹 Lint code with Flake8
        run: |
          echo "🔎 Running flake8 for style check..."
          flake8 .
          echo "✅ Flake8 completed."

      - name: 🧪 Run tests with Pytest
        run: |
          echo "🚀 Launching test suite..."
          pytest
